### ISSUE TITLE
special Version is gone

### ISSUE THREAD

**Issue by Charly333** [Royrdan/Octoprint-Smart-Filament-Sensor#11]
Hi, there was a version for 4 nozzle Printers, that was done within the first developing time. The link was here in an issue. can´t find it any more and need it for after changing to phyton 3 the old version was substituted by the new version only supporting one sensor. 

Could you hand back that link?

Reg. Charly

**Comment by Royrdan** [comment]
Hi @Charly333,
I have taken over this plugin and do not have the old issues that were in the old repo.
Check out the issues on the old REPO for the 4 nozzle development. I couldnt find it when initially checking though. Please let me know if you find it and I can look into trying to implement this.
Thanks
