### ISSUE TITLE
Update Loop in Version 1.1.6.3

### ISSUE THREAD

**Issue by joshuacant** [Royrdan/Octoprint-Smart-Filament-Sensor#7]
Hi, there's an update loop with the latest release. I update, reload OctoPrint, and then it tells me to do the same update again. There are no errors during installation, however after the update, the version number of the installed plugin does not change. It starts at 1.1.6.1 and remains at 1.1.6.1 afterward, so I get prompted to update to 1.1.6.3 again.

I'm not super familiar with the Octoprint plugin configuration, but I think the problem is that the version number didn't change inside setup.py

That's just a guess though, so I could be completely wrong. Thanks for taking this plugin over, and I appreciate all your hard work on it so far.

**Comment by Royrdan** [comment]
Hi thanks for your feedback. You are correct. I did forget to change the plugin version in setup.py. Still getting my head around the whole setup and which things to modify. Thanks again.
